### ISSUE TITLE
Error while training the model

### ISSUE THREAD

**Issue by supriya-gdptl** [cangumeli/ROCA#10]
Hello @cangumeli,
Sorry to bother you again, but I am getting following error while training the ROCA model.
Appreciate any help.

```
[09/07 15:47:04 d2.evaluation.evaluator]: Inference done 5388/5436. 0.0699 s / img. ETA=0:00:03
[09/07 15:47:07 d2.evaluation.evaluator]: Total inference time: 0:07:07.043241 (0.078631 s / img per device, on 1 devices)
[09/07 15:47:07 d2.evaluation.evaluator]: Total inference pure compute time: 0:06:19 (0.069837 s / img per device, on 1 devices)

Starting per-frame evaluation
Frame: 0/5436
Frame: 500/5436
Frame: 1000/5436
Frame: 1500/5436
Frame: 2000/5436
Frame: 2500/5436
Frame: 3000/5436
Frame: 3500/5436
Frame: 4000/5436
Frame: 4500/5436
Frame: 5000/5436
Traceback (most recent call last):
  File "C:\Users\Anaconda3\envs\roca\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\research\code\roca\network\roca\engine\trainer.py", line 207, in cad_context
    yield
  File "D:\research\code\roca\network\roca\engine\trainer.py", line 180, in test
    results = super().test(cfg, model, evaluators)
  File "d:\research\code\detectron2-0.3\detectron2\engine\defaults.py", line 534, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "d:\research\code\detectron2-0.3\detectron2\evaluation\evaluator.py", line 176, in inference_on_dataset
    results = evaluator.evaluate()
  File "d:\research\code\detectron2-0.3\detectron2\evaluation\evaluator.py", line 91, in evaluate
    result = evaluator.evaluate()
  File "D:\research\code\roca\network\roca\evaluation\per_frame_evaluation.py", line 81, in evaluate
    compute_ap(scores, labels, npos).item() * 100,
AttributeError: 'float' object has no attribute 'item'

```

**Comment by cangumeli** [comment]
Hi. Could you make sure you use the same PyTorch version stated in the README and not something newer or older? It seems like `Python scalar + PyTorch scalar tensor` operation produces a Python scalar in your version or PyTorch scalar API is different somehow. In our version, it was producing a PyTorch scalar tensor where I had to get the `.item()` to get a Python scalar.

In this special case, it should be fine if you just remove `.item()` there in your version btw :).

**Comment by cangumeli** [comment]
Closing due to inactivity, feel free to re-open it if you still have this problem.
