### ISSUE TITLE
Error while rendering data

### ISSUE THREAD

**Issue by holy-zhou-shit** [cangumeli/ROCA#13]
Hello @cangumeli ,

Thank you for sharing the code.

I obtained the dataset based on the code and sh run.sh
I am getting following error while rendering the ROCA data.

Appreciate any help.
Process Process-1:
Traceback (most recent call last):
  File "/home/zhou/anaconda3/envs/roca/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zhou/anaconda3/envs/roca/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "render.py", line 296, in worker
    scene_alignments, scene_images = render_scene(
  File "render.py", line 181, in render_scene
    rasterizer.add_mesh(mesh, idx, camera_to_model)
  File "/home/zhou/下载/ROCA-main/renderer/utils/raster.py", line 88, in add_mesh
    self.add_model(
  File "/home/zhou/下载/ROCA-main/renderer/utils/raster.py", line 123, in add_model
    super().add_model(triangles, vertices, idx, to_noc, normals)
TypeError: add_model(): incompatible function arguments. The following argument types are supported:
    1. (self: scan2cad_rasterizer.Rasterizer, arg0: numpy.ndarray[numpy.uint64], arg1: numpy.ndarray[numpy.float32], arg2: int) -> None
    2. (self: scan2cad_rasterizer.Rasterizer, arg0: numpy.ndarray[numpy.uint64], arg1: numpy.ndarray[numpy.float32], arg2: int, arg3: numpy.ndarray[numpy.float32]) -> None

**Comment by cangumeli** [comment]
Thanks a lot for the issue, I will be looking into it. Until then, could you try re-compiling the code in https://github.com/cangumeli/Scan2CADRasterizer and replace the provided `.so` file `renderer/scan2cad_rasterizer.cpython-38-x86_64-linux-gnu.so` with your new compilation?
